"""Edit table timeslot (service_id, group_class_id)

Revision ID: 098b64bd7813
Revises: 643b829d02a3
Create Date: 2024-12-03 14:38:51.948214

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098b64bd7813'
down_revision: Union[str, None] = '643b829d02a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeslot', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeslot', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
