"""Edit table booking

Revision ID: 11d162f45051
Revises: a59f6a0185fe
Create Date: 2024-11-29 11:41:36.358118

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d162f45051'
down_revision: Union[str, None] = 'a59f6a0185fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('dates', sa.Date(), nullable=False))
    op.alter_column('booking', 'service',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="service::integer")
    op.alter_column('booking', 'master',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="service::integer")
    op.alter_column('booking', 'time',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="service::integer")
    op.drop_column('booking', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('booking', 'time',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="service::text")
    op.alter_column('booking', 'master',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="service::text")
    op.alter_column('booking', 'service',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="service::text")
    op.drop_column('booking', 'dates')
    # ### end Alembic commands ###
