"""Edit relationship

Revision ID: 250064e0b11d
Revises: 218f38811a9d
Create Date: 2024-12-05 15:20:42.592746

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250064e0b11d'
down_revision: Union[str, None] = '218f38811a9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groupclass', sa.Column('trainer_id', sa.Integer(), nullable=True))
    op.add_column('trainergroup', sa.Column('group_class_id', sa.Integer(), nullable=True))
    op.drop_constraint('trainergroup_group_id_fkey', 'trainergroup', type_='foreignkey')
    op.create_foreign_key(None, 'trainergroup', 'groupclass', ['group_class_id'], ['id'])
    op.drop_column('trainergroup', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainergroup', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trainergroup', type_='foreignkey')
    op.create_foreign_key('trainergroup_group_id_fkey', 'trainergroup', 'groupclass', ['group_id'], ['id'])
    op.drop_column('trainergroup', 'group_class_id')
    op.drop_column('groupclass', 'trainer_id')
    # ### end Alembic commands ###
