"""Create relationship table for trainers and services

Revision ID: 2b705e6338e7
Revises: 70d9f694ac3c
Create Date: 2024-12-02 14:50:28.474348

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b705e6338e7'
down_revision: Union[str, None] = '70d9f694ac3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
