"""Edit model service

Revision ID: 6317d58517f4
Revises: e839efd6b1ed
Create Date: 2024-12-09 15:23:36.282870

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6317d58517f4'
down_revision: Union[str, None] = 'e839efd6b1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_groupservices_name', table_name='groupservices')
    op.drop_index('ix_groupservices_price', table_name='groupservices')
    op.drop_table('groupservices')
    op.drop_index('ix_groupspecialists_name', table_name='groupspecialists')
    op.drop_table('groupspecialists')
    op.drop_index('ix_individualservices_name', table_name='individualservices')
    op.drop_index('ix_individualservices_price', table_name='individualservices')
    op.drop_table('individualservices')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_massage_name', table_name='massage')
    op.drop_index('ix_massage_price', table_name='massage')
    op.drop_table('massage')
    op.drop_index('ix_individualspecialists_name', table_name='individualspecialists')
    op.drop_table('individualspecialists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individualspecialists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='individualspecialists_pkey')
    )
    op.create_index('ix_individualspecialists_name', 'individualspecialists', ['name'], unique=False)
    op.create_table('massage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='massage_pkey')
    )
    op.create_index('ix_massage_price', 'massage', ['price'], unique=False)
    op.create_index('ix_massage_name', 'massage', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_table('individualservices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='individualservices_pkey')
    )
    op.create_index('ix_individualservices_price', 'individualservices', ['price'], unique=False)
    op.create_index('ix_individualservices_name', 'individualservices', ['name'], unique=False)
    op.create_table('groupspecialists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groupspecialists_pkey')
    )
    op.create_index('ix_groupspecialists_name', 'groupspecialists', ['name'], unique=False)
    op.create_table('groupservices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='groupservices_pkey')
    )
    op.create_index('ix_groupservices_price', 'groupservices', ['price'], unique=False)
    op.create_index('ix_groupservices_name', 'groupservices', ['name'], unique=False)
    # ### end Alembic commands ###
