"""Delete user_id in booking

Revision ID: bcbf7f1ae69f
Revises: 5f9c4c0896c4
Create Date: 2024-11-29 12:31:08.163792

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbf7f1ae69f'
down_revision: Union[str, None] = '5f9c4c0896c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'dates',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using="dates::date")
    op.drop_index('ix_booking_user_id', table_name='booking')
    op.drop_column('booking', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_booking_user_id', 'booking', ['user_id'], unique=False)
    op.alter_column('booking', 'dates',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
