networks:
  dev:

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './cms_backend/app/public:/public'
    depends_on:
      - cms_backend
      - auth_backend
      - backend
      - frontend
    networks:
      - dev

  auth_backend:
    build:
      context: ./auth/auth_backend
    ports:
      - "8001:8000"
    volumes:
      - ./auth/auth_backend/app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/authusers
    networks:
      - dev

  cms_backend:
    build:
      context: ./cms_backend
    ports:
      - "8003:8000"
    volumes:
      - ./cms_backend/app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/Users
    networks:
      - dev

  backend:
    build: 
      context: ./application/backend
    ports:
      - "8002:8000"
    depends_on:
       - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/Users
    networks:
      - dev
    volumes:
      - ./application/backend:/app

  frontend:
    build: 
      context: ./application/frontend
    ports:
      - "3001:3000"
    networks:
      - dev

  auth_frontend:
    build: 
      context: ./auth/auth_frontend
    ports:
      - "3002:3000"
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Worldof123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  admin_backend:
    build: 
      context: ./admin/backend
    ports:
      - "5001:5000"
    depends_on:
       - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/Users
    networks:
      - dev
    volumes:
      - ./admin/backend:/app

  admin_frontend:
    build: 
      context: ./admin/frontend
    ports:
      - "3003:3000"
    networks:
      - dev

  # rabbitmq:
  #   image: rabbitmq:latest
  #   hostname: rabbitmq
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   networks:
  #     - dev


volumes:
  postgres_data: