networks:
  dev:

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
      - './backend/public:/public'
      - './backend/static:/static'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
       - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/Users
    networks:
      - dev

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dev

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Worldof123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  postgres_data:
