networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './public:/public'
      - './static:/static'
    depends_on:
      - backend
    networks:
      - dev

  backend:
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - dev

