networks:
  auth:

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - './nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf'
    depends_on:
      - auth_backend
      - auth_frontend
    networks:
      - auth

  auth_backend:
    build:
      context: ./auth_backend
    ports:
      - "8001:8000"
    volumes:
      - ./auth_backend/app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:Worldof123@postgres:5432/authusers
    networks:
      - auth

  auth_frontend:
    build: 
      context: ./auth_frontend
    ports:
      - "3002:3000"
    networks:
      - auth

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: authusers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Worldof123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth


volumes:
  postgres_data: