"""Edit TelegramOTP add Admins

Revision ID: a2809ebc12d5
Revises: cf26bafb4eb9
Create Date: 2025-01-11 12:30:28.724778

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2809ebc12d5'
down_revision: Union[str, None] = 'cf26bafb4eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramotp', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramotp', 'is_admin')
    # ### end Alembic commands ###
