"""Create tables IndividualSpecialists, IndividualServices, Massage, GroupSpecialists, GroupServices, Booking

Revision ID: 6330445429fc
Revises: ef0775ee4223
Create Date: 2024-11-27 18:44:52.819056

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6330445429fc'
down_revision: Union[str, None] = 'ef0775ee4223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('master', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_user_id'), 'booking', ['user_id'], unique=False)
    op.create_table('groupservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupservices_name'), 'groupservices', ['name'], unique=False)
    op.create_index(op.f('ix_groupservices_price'), 'groupservices', ['price'], unique=False)
    op.create_table('groupspecialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groupspecialists_name'), 'groupspecialists', ['name'], unique=False)
    op.create_table('individualservices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individualservices_name'), 'individualservices', ['name'], unique=False)
    op.create_index(op.f('ix_individualservices_price'), 'individualservices', ['price'], unique=False)
    op.create_table('individualspecialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individualspecialists_name'), 'individualspecialists', ['name'], unique=False)
    op.create_table('massage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_massage_name'), 'massage', ['name'], unique=False)
    op.create_index(op.f('ix_massage_price'), 'massage', ['price'], unique=False)
    op.drop_index('ix_authuser_email', table_name='authuser')
    op.drop_index('ix_authuser_username', table_name='authuser')
    op.drop_table('authuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='authuser_pkey')
    )
    op.create_index('ix_authuser_username', 'authuser', ['username'], unique=True)
    op.create_index('ix_authuser_email', 'authuser', ['email'], unique=True)
    op.drop_index(op.f('ix_massage_price'), table_name='massage')
    op.drop_index(op.f('ix_massage_name'), table_name='massage')
    op.drop_table('massage')
    op.drop_index(op.f('ix_individualspecialists_name'), table_name='individualspecialists')
    op.drop_table('individualspecialists')
    op.drop_index(op.f('ix_individualservices_price'), table_name='individualservices')
    op.drop_index(op.f('ix_individualservices_name'), table_name='individualservices')
    op.drop_table('individualservices')
    op.drop_index(op.f('ix_groupspecialists_name'), table_name='groupspecialists')
    op.drop_table('groupspecialists')
    op.drop_index(op.f('ix_groupservices_price'), table_name='groupservices')
    op.drop_index(op.f('ix_groupservices_name'), table_name='groupservices')
    op.drop_table('groupservices')
    op.drop_index(op.f('ix_booking_user_id'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
