"""Edit table TimeSlot

Revision ID: 643b829d02a3
Revises: 1f37589714d6
Create Date: 2024-12-03 14:16:15.872539

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643b829d02a3'
down_revision: Union[str, None] = '1f37589714d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('group_class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'timeslot', 'groupclass', ['group_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timeslot', type_='foreignkey')
    op.drop_column('timeslot', 'group_class_id')
    # ### end Alembic commands ###
