"""Migrate from SQLite to PostgreSQL

Revision ID: d2df4ab83a50
Revises: 7c79e9d89944
Create Date: 2024-11-02 12:15:09.679339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2df4ab83a50'
down_revision: Union[str, None] = '7c79e9d89944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
