"""Edit Timeslot TO UNIQ

Revision ID: e839efd6b1ed
Revises: 9498e0c46663
Create Date: 2024-12-06 18:03:51.240012

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e839efd6b1ed'
down_revision: Union[str, None] = '9498e0c46663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_time_slot', 'timeslot', ['trainer_id', 'group_class_id', 'dates', 'times'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_time_slot', 'timeslot', type_='unique')
    # ### end Alembic commands ###
