"""add auth user table

Revision ID: ef0775ee4223
Revises: 8408ccc70d69
Create Date: 2024-11-06 13:25:24.813589

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0775ee4223'
down_revision: Union[str, None] = '8408ccc70d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authuser_email'), 'authuser', ['email'], unique=True)
    op.create_index(op.f('ix_authuser_username'), 'authuser', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authuser_username'), table_name='authuser')
    op.drop_index(op.f('ix_authuser_email'), table_name='authuser')
    op.drop_table('authuser')
    # ### end Alembic commands ###
