"""Edit table TimeSlot

Revision ID: f658d7cf4a34
Revises: 10fa7e6116b4
Create Date: 2024-11-28 14:14:05.465126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f658d7cf4a34'
down_revision: Union[str, None] = '10fa7e6116b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('times', sa.Time(), nullable=False))
    op.drop_column('timeslot', 'time')
    op.drop_column('timeslot', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeslot', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('timeslot', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('timeslot', 'times')
    # ### end Alembic commands ###
